### ISSUE TITLE
Make protobuf dependency optional

### ISSUE THREAD

**Issue by abitrolly** [googlecodelabs/codelab-elements#26]
I know that this must be wrong repository, and still - Bazel is so heavy - I almost finished all my data plan. Why it is downloading Chrome? :) Is it necessary to download 200Mb+ just to test one static page?

**Comment by abitrolly** [comment]
And it still doesn't work:
```
➜  codelab-elements git:(master) bazel test --test_output=all //demo:hello_test
Extracting Bazel installation...
................
WARNING: /home/anatoli/.cache/bazel/_bazel_anatoli/e3403aace5e177707d48307c82a8291c/external/com_google_protobuf_java/WORKSPACE:1: Workspace name in /home/anatoli/.cache/bazel/_bazel_anatoli/e3403aace5e177707d48307c82a8291c/external/com_google_protobuf_java/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@com_google_protobuf_java); this will cause a build error in future versions
INFO: Analysed target //demo:hello_test_chromium-local (97 packages loaded).
INFO: Found 1 test target...
ERROR: /home/anatoli/.cache/bazel/_bazel_anatoli/e3403aace5e177707d48307c82a8291c/external/com_google_protobuf_java/BUILD:274:1: C++ compilation of rule '@com_google_protobuf_java//:protoc_lib' failed (Exit 1)
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Target //demo:hello_test_chromium-local failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2612.587s, Critical Path: 0.92s
FAILED: Build did NOT complete successfully

Executed 0 out of 1 test: 1 fails to build.
```

**Comment by x1ddos** [comment]
It is downloading chrome because that's how we run JS tests: all the tests are run using the same browser and its version regardless of what you have installed locally. I would highly recommend avoiding development using any kind of limited data plan.

The error you're getting is coming from an unfortunate protobuf dependency in [rules_closure](https://github.com/bazelbuild/rules_closure) repo. We use rules_closure to compile and optimize javascript and CSS code.

Specifically, you don't seem to have a c++ toolchain installed. It is an unfortunate requirement for using rules_closure repo. I will create an issue in their repo and cross-reference here.

**Comment by x1ddos** [comment]
Actually, I think we could just remove protobuf dependency alltogether, at least for now because we're not using it all.

**Comment by x1ddos** [comment]
After a bit of researching, turns out ClosureWorker requires protobuf. For instance, [build_info.proto](https://github.com/bazelbuild/rules_closure/blob/fab2c6b1d5eeaf0b1a067054e425e8c38f667d40/java/io/bazel/rules/closure/build_info.proto).

So, I don't think we'll be able to completely remove protobuf dependency. One thing I could try is to replace compile-from-source protoc with precompiled version fetching from their [releases](https://github.com/google/protobuf/releases) as described in https://github.com/google/protobuf#protocol-compiler-installation.

**Comment by x1ddos** [comment]
Actually, I've just realized we're also using SCSS, which is again compiled from source. So, I guess gcc is required.

I'll be making a public servable demo in #25. If you just want to try it out or get the precompiled JS and CSS artifacts, you'll be able to do so without the dev tools we're using.

**Comment by abitrolly** [comment]
So how to at least fetch protobuf from releases? This will speed up the build, right?

**Comment by x1ddos** [comment]
Yes, this would speed up the build. Both rules_closure and rules_go depend on protobuf:
  - https://github.com/bazelbuild/rules_closure/blob/f04ee869600de61ca7ab822fa9014fda810b2428/java/io/bazel/rules/closure/worker/BUILD#L32
  - https://github.com/bazelbuild/rules_closure/search?utf8=%E2%9C%93&q=com_google_protobuf&type=Code
  - https://github.com/bazelbuild/rules_go/blob/67f44035d84a352cffb9465159e199066ecb814c/proto/compiler.bzl#L132
  - https://github.com/bazelbuild/rules_go/search?utf8=%E2%9C%93&q=com_google_protobuf&type=Code

So, I believe this would require:

  1. Fetch prebuilt `protoc` package from [releases](https://github.com/google/protobuf/releases) based on the current OS/arch, though: linux vs macos vs windows.
  2. Stub out `@com_google_protobuf//:...` with the prebuilt `protoc` fetched in the prev. step before importing rules_closure and rules_go repositories in the WORKSPACE.
  3. Add `omit_com_google_protobuf=True` to [closure_repositories()](https://github.com/googlecodelabs/codelab-elements/blob/19ceafa3c1ee77dd8dccae778865762a70773704/WORKSPACE#L22) in our WORKSPACE.

**Comment by shawnbuso** [comment]
Tracking in https://github.com/googlecodelabs/tools/issues/129
